Feature/skale 3060 transfer funds
skalenetwork/validator-cli pull request #163
Opened 2020-08-14 16:10 UTC by DmytroNazarenko

2020-08-14 16:37 UTC, dmytrotkk submitted a review, later dismissed
Great!

2020-08-17 07:42 UTC, badrogger requested changes

2020-08-17 07:42 UTC, badrogger commented on cli/wallet.py
> +def _send_eth(receiver_address, amount, pk_file):
I think we should move the sending logic to core package and leave only output operations here

2020-08-17 07:42 UTC, badrogger commented on tests/cli/wallet_test.py
> +    address = skale.wallet.address
I think we should add test to check actual amount of ETH tokens before and after sending operations for both sender and receiver accounts.

2020-08-17 10:50 UTC, badrogger approved these changes

2020-08-17 11:15 UTC, dmytrotkk approved these changes

2020-08-17 11:16 UTC, merged